#
# This file contains configuration flags to customize your site
#
theme: jekyll-theme-architect
# Name of your site (displayed in the header)
name: Jaggu's World 

# Short bio or description (displayed in the header)
description: Artificial Intelligence and Analytics Leader | Sr. Manager Projects

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://media.licdn.com/dms/image/C4E03AQEWH2RFcU0KaA/profile-displayphoto-shrink_200_200/0?e=1560988800&v=beta&t=BL2VFGRofApOyU3jUxcnhdsNpPR3zjGPQMyPsINZlRA
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
#https://media.licdn.com/mpr/mpr/shrink_100_100/AAEAAQAAAAAAAAOcAAAAJDlmODlmZTAxLTYxN2QtNDU1Yy05YzQwLTEzNzRlYWY0NDQxZQ.jpg
#
# Flags below are optional
#


author:
  name: Jagan
  description: Artificial Intelligence and Analytics Leader | Sr. Manager Projects
  #gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/jaganadhg
    github:    https://github.com/jaganadhg

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: jaganadhg
  instagram:
  linkedin: jaganadhg
  pinterest:
  rss: jaganadhg # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: jaganadhg
  stackoverflow: users/706737/jaganadh-gopinadhan
  youtube: jaganadhg/videos


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus_short_name: jaganadhg	
#disqus_show_comment_count: true

disqus: jaganadhg

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-36497233-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#
markdown: kramdown
#markdown: redcarpet
#markdown: maruku
highlighter: rouge
permalink: /:title/
# The release of Jekyll Now that you're using
version: 3.8.5
#version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - jekyll-seo-tag

github:
  repo: https://github.com/jaganadhg/jaganadhg.github.io/

nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://jaganadhg.github.io/'


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

paginate: 1
paginate_path: "/page/:num/"

mathjax: true
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
